### ISSUE TITLE
Revisit and do input validation properly

### ISSUE THREAD

**Issue by mabdh** [raystack/frontier#159]
**Is your feature request related to a problem? Please describe.**
Most of input in shield are not properly checked, there was even a case where an empty string is allowed as an ID and could be stored in the DB. We need to have a proper input validation and sanitization for shield.

**Describe the solution you'd like**
We can implement input validation and sanitization in handler layer so we can return early if there is an error (the code must not executing unnecessary processing down to the repository layer).

**Comment by ravisuhag** [comment]
Some of these validations can also happen at GRPC api layer as well.

**Comment by kushsharma** [comment]
I see in proto files there are validation rules of [protoc](https://github.com/bufbuild/protoc-gen-validate) defined but we don't really validate them per request. Simply adding `request.ValidateAll()` in the GRPC handler should be able to handle it.

**Comment by ravisuhag** [comment]
@kushsharma is this still applicable?

**Comment by kushsharma** [comment]
Most of the APIs have validation now.
