### ISSUE TITLE
Support storage of profile picture of user and organization

### ISSUE THREAD

**Issue by anujk14** [raystack/frontier#291]
**Is your feature request related to a problem? Please describe.**
Frontier should provide support for the following:

1. Users to upload profile pictures
2. Organizations to upload their logo

Profile images and logos provide easy identification of users and organizations, making collaboration easier

**Describe the solution you'd like**
Frontend:

- The frontend SDK would provide a way for the user to upload a profile image
- The frontend SDK would provide a way to upload organization image (logo)
- The frontend SDK would encode the images using base64 encoding and send it to the Frontier backend
- Images need to be restricted to a particular size. This should be configurable on the SDK and the validation of the same would be applied on the frontend

Backend:

- Two new columns would be introduced for storage of images:
    - Profile picture column on users table
    - Logo column on organization table
- The backend would have a configurable option for the kind of storage to be used for images. Initially, there will be only one way of supporting images, which is to store base64 encoded images in the database directly. This config allows for future extensibility, where we could support other image stores like S3, and save S3 links in our database.

**Describe alternatives you've considered**

- Instead of introducing new columns to users and organizations, an alternate approach of using the metaschema to support image storage. However, profile images and logos are a very core functionality, and it was decided to not use metaschema since that can be completely overriden by users integrating with Frontier

**Comment by kushsharma** [comment]
The backend has started supporting taking profile picture with an attribute named `avatar` now in the default resource APIs.
