### ISSUE TITLE
Installation with .deb files does not bundle UI for SPA

### ISSUE THREAD

**Issue by c-nv-s** [raystack/frontier#455]
**Describe the bug**
when installing frontier via .deb files from the releases page then the files for the single page app are not included.

```
 warn    failed to load spa[err ui is enabled but no index.html found: open index.html: file does not exist]    {"err": "ui is enabled but no index.html found: open index.html: file does not exist"}
```

**To Reproduce**
1. Install necessary dependancies
2. install frontier via .deb file... init to and fill in the generated config file
3. run ``frontier server start``

**Expected behavior**
1. Either the required UI files should be packaged in the .deb release and the app look for it at a default location after install or
2. The binary should [embed the necessary UI files](https://pkg.go.dev/embed) as default and provide a flag via the cli where the user can override the location to find the relevant files.

**Desktop (please complete the following information):**
 - OS: debian bullseye
 - Version 0.8.15

**Comment by rsbh** [comment]
This issue has been fixed in [this PR](https://github.com/raystack/frontier/pull/460)
The UI is bundled with binary now.

**Comment by c-nv-s** [comment]
@rsbh I'm not sure how that pull request was tested, but to put it simply, if someone could please show me the repeatable steps of how to install via the .deb file and then get access to the admin ui (which is apparently supposed to be at ``/console`` once the service is up and running, that would be amazing.

I managed to get the latest version and re-attempt the install but now I am seeing ``error   ui server failed: no port specified[]``
the code seems to show you've introduced a UIConfig now but there isn't any entry for it in the ``config.yaml`` or environment variable to set for it.
...Additionally, what will happen if that new ui port variable is different from the ``app.port`` variable in the config file??

**Comment by rsbh** [comment]
The admin console will now work in different port from api server port instead of `/console` path.
To run the admin UI, you need to set the port number. 
you can either set port number in `FRONTIER_UI_PORT` env variable or pass `ui.port` in config file.

**Comment by c-nv-s** [comment]
ok thank you for letting me know.
I appreciate the hard work that is going into this application, so please understand I'm not complaining, but it might be useful if your team includes a documentation update task as part of your "definition of done" for each feature/ticket. That way everything stays in sync with each release.
